<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;
    
    /**
     * @var string $mobile_token
     */
    protected $mobile_token;
    
    /**
     * @var int $points
     */
    protected $points;
    
    /**
     * @var array $feedbacks
     */
    protected $feedbacks;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->feedbacks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Get points
     * 
     * @return int $points
     */
    public function getPoints() 
    {
        return $this->points;
    }
    
    /**
     * Set points
     * 
     * @return int $points
     */
    public function setPoints($points) {
        $this->points = $points;
        
        return $this->points;
    }

    /**
     * Get the mobile token
     */
    public function getMobileToken() 
    {        
        return $this->mobile_token;
    }  
    
    public function setMobileToken() {
        $this->mobile_token = md5(str_shuffle(date("Y-m-d h:i:sa")  . $this->getUsername()));
    }    

    /**
     * 
     * @param \AppBundle\Entity\Feedback $feedback
     */    
    public function addFeedback(\AppBundle\Entity\Feedback $feedback) {
        $this->feedbacks[] = $feedback;
    }
}
